name: Run Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

   - name: Install ChromeDriver and Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo ln -sf /usr/bin/chromium-browser /usr/bin/google-chrome

    - name: Run tests
      run: |
        pytest tests/ > result.log || true

    - name: Send Telegram message
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        python telegram_notify.py "$(tail -n 20 result.log)"
